<?php
/**
 * Lot d'amorçage — École de foot + Préformation (tranches G, F, E, D).
 *
 * Tous en `en_revue`, `source = cree_meyrin`. Géométries complètes (zone,
 * joueurs numérotés, matériel, mouvements ordonnés avec acteur pour l'anim).
 * Chargé par seed/seed_exercices.php.
 *
 * Premier lot fonctionnel : couvre les 4 phases EASI pour que le générateur
 * produise des séances conformes. Le quota complet du §11 (6 éch / 8 ana /
 * 10 sit / 10 jeu / 3 gardien par périmètre) se complète ensuite.
 */

declare(strict_types=1);

$P = ['ecole_foot', 'preformation', 'foot_libre_filles'];

return [$P, [

/* ================================================= ÉCHAUFFEMENT (6) */
[
    'code' => 'ECH-PASS5', 'titre' => 'Réveil articulaire en cercle',
    'objectif_principal' => 'Activer le corps et le regard avant la séance',
    'categorie_technique' => 'echauffement', 'phase_easi' => 'echauffement',
    'accents' => ['CO'], 'tranches_age' => ['G', 'F', 'E', 'D'], 'filieres' => ['loisir', 'competition'],
    'genre' => 'mixte', 'joueurs_min' => 6, 'joueurs_max' => 16,
    'surface_type' => 'zone_libre', 'surface_largeur' => 18, 'surface_longueur' => 18,
    'duree_min' => 8, 'duree_max' => 14,
    'materiel' => [['type' => 'coupelle', 'qte' => 6], ['type' => 'ballon', 'qte' => 2]],
    'description_deroulement' => "Les joueurs forment un cercle. Mobilité articulaire guidée (chevilles, hanches, épaules) puis passes à la main en suivant sa passe. Ajouter un 2e ballon.",
    'consignes_coach' => "Amplitude progressive, jamais à froid. Le joueur annonce le prénom avant de passer.",
    'criteres_reussite' => "Aucun ballon au sol pendant 30 secondes avec deux ballons.",
    'variante_facile' => "Un seul ballon, passe au voisin.", 'variante_difficile' => "Passe au pied, de l'intérieur.",
    'geometrie' => ['zone' => ['type' => 'zone_libre', 'longueur' => 18, 'largeur' => 18],
        'joueurs' => [
            ['x' => 9, 'y' => 2, 'equipe' => 'neutre'], ['x' => 15, 'y' => 5, 'equipe' => 'neutre'],
            ['x' => 16, 'y' => 12, 'equipe' => 'neutre'], ['x' => 11, 'y' => 16, 'equipe' => 'neutre'],
            ['x' => 4, 'y' => 14, 'equipe' => 'neutre'], ['x' => 2, 'y' => 7, 'equipe' => 'neutre'],
        ],
        'mouvements' => [
            ['from' => [9, 2], 'to' => [16, 12], 'type' => 'passe', 'ordre' => 1],
            ['from' => [16, 12], 'to' => [4, 14], 'type' => 'passe', 'ordre' => 2],
            ['from' => [4, 14], 'to' => [15, 5], 'type' => 'passe', 'ordre' => 3],
        ]],
],
[
    'code' => 'ECH-MIROIR', 'titre' => 'Jeu du miroir avec ballon',
    'objectif_principal' => 'Coordination, prise d\'information visuelle',
    'categorie_technique' => 'echauffement', 'phase_easi' => 'echauffement',
    'accents' => ['CO', 'TE'], 'tranches_age' => ['G', 'F', 'E'], 'filieres' => ['loisir', 'competition'],
    'genre' => 'mixte', 'joueurs_min' => 8, 'joueurs_max' => 16,
    'surface_type' => 'quart', 'surface_largeur' => 20, 'surface_longueur' => 20,
    'duree_min' => 8, 'duree_max' => 12,
    'materiel' => [['type' => 'cone', 'qte' => 8], ['type' => 'ballon', 'qte' => 8]],
    'description_deroulement' => "Par deux face à face, chacun un ballon. Le meneur conduit, feinte, change de rythme ; le partenaire reproduit en miroir. Inverser les rôles toutes les 45 s.",
    'consignes_coach' => "Tête haute, ballon proche du pied. On regarde le partenaire, pas son ballon.",
    'criteres_reussite' => "Le suiveur reste synchrone sur 3 changements de direction.",
    'variante_facile' => "Sans ballon, déplacements seulement.", 'variante_difficile' => "Sur signal, le suiveur devient meneur.",
    'geometrie' => ['zone' => ['type' => 'quart', 'longueur' => 20, 'largeur' => 20],
        'joueurs' => [
            ['x' => 8, 'y' => 6, 'equipe' => 'A', 'label' => '1'], ['x' => 12, 'y' => 6, 'equipe' => 'B', 'label' => '1'],
            ['x' => 8, 'y' => 14, 'equipe' => 'A', 'label' => '2'], ['x' => 12, 'y' => 14, 'equipe' => 'B', 'label' => '2'],
        ],
        'materiel' => [['type' => 'ballon', 'x' => 8, 'y' => 6], ['type' => 'ballon', 'x' => 8, 'y' => 14]],
        'mouvements' => [
            ['from' => [8, 6], 'to' => [10, 10], 'type' => 'conduite', 'ordre' => 1, 'acteur' => '1'],
        ]],
],
[
    'code' => 'ECH-TRIANGLE', 'titre' => 'Passe et suit en triangle',
    'objectif_principal' => 'Qualité de passe et déplacement après la passe',
    'categorie_technique' => 'echauffement', 'phase_easi' => 'echauffement',
    'accents' => ['TE'], 'tranches_age' => ['E', 'D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 6, 'joueurs_max' => 12,
    'surface_type' => 'quart', 'surface_largeur' => 22, 'surface_longueur' => 22,
    'duree_min' => 8, 'duree_max' => 14,
    'materiel' => [['type' => 'coupelle', 'qte' => 3], ['type' => 'ballon', 'qte' => 2]],
    'description_deroulement' => "Trois plots en triangle, un groupe à chaque plot. Passe à droite, puis on suit sa passe pour prendre la place suivante. Sens inverse au signal.",
    'consignes_coach' => "Passe appuyée au sol, pied d'appui orienté vers la cible. Contrôle orienté vers le plot suivant.",
    'criteres_reussite' => "10 passes d'affilée sans ballon perdu.",
    'variante_facile' => "Deux touches autorisées.", 'variante_difficile' => "Une touche, puis passe en une touche.",
    'geometrie' => ['zone' => ['type' => 'quart', 'longueur' => 22, 'largeur' => 22],
        'joueurs' => [
            ['x' => 4, 'y' => 4, 'equipe' => 'A', 'label' => '1'],
            ['x' => 18, 'y' => 4, 'equipe' => 'A', 'label' => '2'],
            ['x' => 11, 'y' => 19, 'equipe' => 'A', 'label' => '3'],
        ],
        'groupes' => [['x' => 2, 'y' => 9, 'nombre' => 3]],
        'materiel' => [['type' => 'coupelle', 'x' => 4, 'y' => 4], ['type' => 'coupelle', 'x' => 18, 'y' => 4], ['type' => 'coupelle', 'x' => 11, 'y' => 19]],
        'mouvements' => [
            ['from' => [4, 4], 'to' => [18, 4], 'type' => 'passe', 'ordre' => 1],
            ['from' => [4, 4], 'to' => [18, 4], 'type' => 'course', 'ordre' => 1, 'acteur' => '1'],
            ['from' => [18, 4], 'to' => [11, 19], 'type' => 'passe', 'ordre' => 2],
            ['from' => [18, 4], 'to' => [11, 19], 'type' => 'course', 'ordre' => 2, 'acteur' => '2'],
            ['from' => [11, 19], 'to' => [4, 4], 'type' => 'passe', 'ordre' => 3],
        ]],
],
[
    'code' => 'ECH-COURSE', 'titre' => 'Parcours de motricité',
    'objectif_principal' => 'Coordination, appuis, changements d\'appui',
    'categorie_technique' => 'coordination', 'phase_easi' => 'echauffement',
    'accents' => ['CO'], 'tranches_age' => ['G', 'F', 'E', 'D'], 'filieres' => ['loisir', 'competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 6, 'joueurs_max' => 18,
    'surface_type' => 'zone_libre', 'surface_largeur' => 12, 'surface_longueur' => 24,
    'duree_min' => 8, 'duree_max' => 12,
    'materiel' => [['type' => 'echelle', 'qte' => 1], ['type' => 'haie', 'qte' => 4], ['type' => 'cone', 'qte' => 6]],
    'description_deroulement' => "Échelle de rythme (un appui par caisson), franchissement de 4 haies basses, slalom entre 6 cônes, retour en trottinant. 3 passages.",
    'consignes_coach' => "Bras actifs, regard loin. On cherche la fréquence d'appuis, pas la vitesse pure.",
    'criteres_reussite' => "Aucun caisson touché sur l'échelle, réception équilibrée après les haies.",
    'variante_facile' => "Marche sur l'échelle, 2 haies.", 'variante_difficile' => "Un pied dans chaque caisson en pas chassés.",
    'geometrie' => ['zone' => ['type' => 'zone_libre', 'longueur' => 24, 'largeur' => 12],
        'materiel' => [
            ['type' => 'echelle', 'x' => 4, 'y' => 6],
            ['type' => 'haie', 'x' => 10, 'y' => 6], ['type' => 'haie', 'x' => 13, 'y' => 6], ['type' => 'haie', 'x' => 16, 'y' => 6],
            ['type' => 'cone', 'x' => 20, 'y' => 4], ['type' => 'cone', 'x' => 21, 'y' => 8],
        ],
        'joueurs' => [['x' => 2, 'y' => 6, 'equipe' => 'neutre']],
        'groupes' => [['x' => 1, 'y' => 3, 'nombre' => 4]],
        'mouvements' => [['from' => [2, 6], 'to' => [22, 6], 'type' => 'course', 'ordre' => 1, 'acteur' => '1']]],
],
[
    'code' => 'ECH-1B2', 'titre' => 'Passe à cinq d\'échauffement (5 contre 2)',
    'objectif_principal' => 'Mise en action, conservation courte',
    'categorie_technique' => 'jeu', 'phase_easi' => 'echauffement',
    'accents' => ['TE', 'TA'], 'tranches_age' => ['E', 'D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 7, 'joueurs_max' => 14,
    'surface_type' => 'quart', 'surface_largeur' => 12, 'surface_longueur' => 12,
    'duree_min' => 8, 'duree_max' => 12,
    'materiel' => [['type' => 'coupelle', 'qte' => 4], ['type' => 'ballon', 'qte' => 2]],
    'description_deroulement' => "Carré de 12 m, 5 joueurs autour, 2 récupérateurs au centre. Conservation. Celui qui perd le ballon ou fait la mauvaise passe va au centre.",
    'consignes_coach' => "Se rendre disponible sur les côtés du porteur, pas dans son dos. Passe au sol.",
    'criteres_reussite' => "8 passes avant récupération.",
    'variante_facile' => "6 contre 2, deux touches.", 'variante_difficile' => "Une touche obligatoire.",
    'geometrie' => ['zone' => ['type' => 'quart', 'longueur' => 12, 'largeur' => 12],
        'joueurs' => [
            ['x' => 2, 'y' => 2, 'equipe' => 'A', 'label' => '1'], ['x' => 10, 'y' => 2, 'equipe' => 'A', 'label' => '2'],
            ['x' => 10, 'y' => 10, 'equipe' => 'A', 'label' => '3'], ['x' => 2, 'y' => 10, 'equipe' => 'A', 'label' => '4'],
            ['x' => 6, 'y' => 1, 'equipe' => 'A', 'label' => '5'],
            ['x' => 5, 'y' => 6, 'equipe' => 'B', 'label' => '1'], ['x' => 7, 'y' => 7, 'equipe' => 'B', 'label' => '2'],
        ],
        'mouvements' => [
            ['from' => [2, 2], 'to' => [10, 2], 'type' => 'passe', 'ordre' => 1],
            ['from' => [10, 2], 'to' => [10, 10], 'type' => 'passe', 'ordre' => 2],
            ['from' => [10, 10], 'to' => [2, 10], 'type' => 'passe', 'ordre' => 3],
        ]],
],
[
    'code' => 'ECH-RONDE', 'titre' => 'Ronde de passes en mouvement',
    'objectif_principal' => 'Passe en mouvement, timing du soutien',
    'categorie_technique' => 'technique', 'phase_easi' => 'echauffement',
    'accents' => ['TE'], 'tranches_age' => ['F', 'E', 'D'], 'filieres' => ['loisir', 'competition'],
    'genre' => 'mixte', 'joueurs_min' => 6, 'joueurs_max' => 12,
    'surface_type' => 'quart', 'surface_largeur' => 20, 'surface_longueur' => 20,
    'duree_min' => 8, 'duree_max' => 12,
    'materiel' => [['type' => 'cone', 'qte' => 4], ['type' => 'ballon', 'qte' => 2]],
    'description_deroulement' => "Quatre stations en carré. Le ballon tourne, chaque joueur suit sa passe. Après 1 minute, on ajoute un 2e ballon en sens inverse.",
    'consignes_coach' => "Communiquer avant de recevoir. Contrôle orienté dans le sens de la passe.",
    'criteres_reussite' => "Deux ballons qui tournent 20 s sans collision.",
    'variante_facile' => "Un ballon.", 'variante_difficile' => "Passe puis sprint vers la station opposée.",
    'geometrie' => ['zone' => ['type' => 'quart', 'longueur' => 20, 'largeur' => 20],
        'joueurs' => [
            ['x' => 3, 'y' => 3, 'equipe' => 'A', 'label' => '1'], ['x' => 17, 'y' => 3, 'equipe' => 'A', 'label' => '2'],
            ['x' => 17, 'y' => 17, 'equipe' => 'A', 'label' => '3'], ['x' => 3, 'y' => 17, 'equipe' => 'A', 'label' => '4'],
        ],
        'materiel' => [['type' => 'cone', 'x' => 3, 'y' => 3], ['type' => 'cone', 'x' => 17, 'y' => 3], ['type' => 'cone', 'x' => 17, 'y' => 17], ['type' => 'cone', 'x' => 3, 'y' => 17]],
        'mouvements' => [
            ['from' => [3, 3], 'to' => [17, 3], 'type' => 'passe', 'ordre' => 1],
            ['from' => [3, 3], 'to' => [17, 3], 'type' => 'course', 'ordre' => 1, 'acteur' => '1'],
            ['from' => [17, 3], 'to' => [17, 17], 'type' => 'passe', 'ordre' => 2],
        ]],
],

/* ================================================= ANALYTIQUE (6) */
[
    'code' => 'ANA-CONDUITE', 'titre' => 'Conduite de balle en slalom chronométré',
    'objectif_principal' => 'Conduite proche du pied, changements de direction',
    'categorie_technique' => 'technique', 'phase_easi' => 'analytique',
    'accents' => ['TE'], 'tranches_age' => ['G', 'F', 'E'], 'filieres' => ['loisir', 'competition'],
    'genre' => 'mixte', 'joueurs_min' => 6, 'joueurs_max' => 16,
    'surface_type' => 'quart', 'surface_largeur' => 10, 'surface_longueur' => 20,
    'duree_min' => 10, 'duree_max' => 18,
    'materiel' => [['type' => 'cone', 'qte' => 6], ['type' => 'ballon', 'qte' => 6]],
    'description_deroulement' => "Slalom de 6 cônes espacés de 2 m, aller en conduite pied droit, retour pied gauche. Deux colonnes en opposition, on encourage.",
    'consignes_coach' => "Petites touches, ballon toujours à moins d'un mètre. Regard qui alterne ballon / cône suivant.",
    'criteres_reussite' => "Aucun cône touché, ballon jamais lâché à plus de 2 m.",
    'variante_facile' => "Cônes espacés de 3 m, un seul pied.", 'variante_difficile' => "Semelle sur chaque cône, conduite extérieur du pied.",
    'geometrie' => ['zone' => ['type' => 'quart', 'longueur' => 20, 'largeur' => 10],
        'joueurs' => [['x' => 2, 'y' => 5, 'equipe' => 'neutre']],
        'groupes' => [['x' => 1, 'y' => 2, 'nombre' => 4]],
        'materiel' => array_map(fn($i) => ['type' => 'cone', 'x' => 4 + $i * 2.5, 'y' => 5], range(0, 5)),
        'mouvements' => [['from' => [2, 5], 'to' => [18, 5], 'type' => 'conduite', 'ordre' => 1, 'acteur' => '1']]],
],
[
    'code' => 'ANA-CONTROLE', 'titre' => 'Contrôle orienté en losange',
    'objectif_principal' => 'Premier contrôle orienté vers l\'espace libre',
    'categorie_technique' => 'technique', 'phase_easi' => 'analytique',
    'accents' => ['TE'], 'tranches_age' => ['E', 'D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 8, 'joueurs_max' => 16,
    'surface_type' => 'demi', 'surface_largeur' => 25, 'surface_longueur' => 20,
    'duree_min' => 12, 'duree_max' => 20,
    'materiel' => [['type' => 'coupelle', 'qte' => 4], ['type' => 'ballon', 'qte' => 2]],
    'description_deroulement' => "Losange de 4 plots. Le joueur reçoit d'un côté, contrôle orienté et passe au plot suivant, puis suit. Changer de sens.",
    'consignes_coach' => "Le corps s'ouvre AVANT le contrôle. Premier contact vers l'avant, pas dans les pieds.",
    'criteres_reussite' => "Contrôle en une touche orienté dans le bon sens 8 fois sur 10.",
    'variante_facile' => "Passe à la main, contrôle du pied.", 'variante_difficile' => "Contrôle d'une surface imposée (extérieur, semelle).",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 20, 'largeur' => 25],
        'joueurs' => [
            ['x' => 10, 'y' => 2, 'equipe' => 'A', 'label' => '1'],
            ['x' => 18, 'y' => 12, 'equipe' => 'A', 'label' => '2'],
            ['x' => 10, 'y' => 23, 'equipe' => 'A', 'label' => '3'],
            ['x' => 2, 'y' => 12, 'equipe' => 'A', 'label' => '4'],
        ],
        'mouvements' => [
            ['from' => [10, 2], 'to' => [18, 12], 'type' => 'passe', 'ordre' => 1],
            ['from' => [18, 12], 'to' => [10, 23], 'type' => 'passe', 'ordre' => 2],
            ['from' => [18, 12], 'to' => [10, 23], 'type' => 'course', 'ordre' => 2, 'acteur' => '2'],
        ]],
],
[
    'code' => 'ANA-PASSE-COURTE', 'titre' => 'Passes courtes / longues alternées',
    'objectif_principal' => 'Dosage de la passe, prise d\'information',
    'categorie_technique' => 'technique', 'phase_easi' => 'analytique',
    'accents' => ['TE', 'TA'], 'tranches_age' => ['D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 8, 'joueurs_max' => 14,
    'surface_type' => 'demi', 'surface_largeur' => 20, 'surface_longueur' => 30,
    'duree_min' => 12, 'duree_max' => 18,
    'materiel' => [['type' => 'coupelle', 'qte' => 5], ['type' => 'ballon', 'qte' => 2]],
    'description_deroulement' => "Circuit en Z : passe courte, appui, passe longue vers la station éloignée, on suit. Travailler les deux pieds.",
    'consignes_coach' => "Passe courte au sol appuyée, passe longue tendue à mi-hauteur. Annoncer 'appui' ou 'profondeur'.",
    'criteres_reussite' => "Passe longue reçue dans la course sans rupture de rythme.",
    'variante_facile' => "Toutes les passes au sol.", 'variante_difficile' => "Passe longue à ras de terre entre deux plots.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 30, 'largeur' => 20],
        'joueurs' => [
            ['x' => 3, 'y' => 3, 'equipe' => 'A', 'label' => '1'],
            ['x' => 8, 'y' => 10, 'equipe' => 'A', 'label' => '2'],
            ['x' => 27, 'y' => 6, 'equipe' => 'A', 'label' => '3'],
        ],
        'mouvements' => [
            ['from' => [3, 3], 'to' => [8, 10], 'type' => 'passe', 'ordre' => 1],
            ['from' => [8, 10], 'to' => [27, 6], 'type' => 'passe', 'ordre' => 2],
        ]],
],
[
    'code' => 'ANA-DUEL', 'titre' => 'Duel 1 contre 1 face au but',
    'objectif_principal' => 'Élimination en dribble, prise de vitesse',
    'categorie_technique' => 'technique', 'phase_easi' => 'analytique',
    'accents' => ['TE'], 'tranches_age' => ['E', 'D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 6, 'joueurs_max' => 14,
    'surface_type' => 'quart', 'surface_largeur' => 16, 'surface_longueur' => 20,
    'duree_min' => 12, 'duree_max' => 18,
    'materiel' => [['type' => 'mini_but', 'qte' => 1], ['type' => 'cone', 'qte' => 2], ['type' => 'ballon', 'qte' => 4]],
    'description_deroulement' => "Attaquant ballon au pied, défenseur passif puis semi-actif. But sur mini-cage. On alterne les rôles. Deux colonnes.",
    'consignes_coach' => "Attaquer l'appui du défenseur, accélérer APRÈS la feinte. Fixer avant d'éliminer.",
    'criteres_reussite' => "3 éliminations réussies sur 5 tentatives.",
    'variante_facile' => "Défenseur passif, mains dans le dos.", 'variante_difficile' => "Défenseur actif, retour au duel autorisé.",
    'geometrie' => ['zone' => ['type' => 'quart', 'longueur' => 20, 'largeur' => 16],
        'joueurs' => [
            ['x' => 2, 'y' => 8, 'equipe' => 'A', 'label' => '1'],
            ['x' => 11, 'y' => 8, 'equipe' => 'B', 'label' => '1'],
        ],
        'materiel' => [['type' => 'mini_but', 'x' => 20, 'y' => 8]],
        'mouvements' => [
            ['from' => [2, 8], 'to' => [10, 5], 'type' => 'conduite', 'ordre' => 1, 'acteur' => '1'],
            ['from' => [10, 5], 'to' => [20, 8], 'type' => 'tir', 'ordre' => 2],
        ]],
],
[
    'code' => 'ANA-JONGLE', 'titre' => 'Ateliers de jonglage progressif',
    'objectif_principal' => 'Relation pied-ballon, surfaces de contact',
    'categorie_technique' => 'technique', 'phase_easi' => 'analytique',
    'accents' => ['TE', 'CO'], 'tranches_age' => ['F', 'E', 'D'], 'filieres' => ['loisir', 'competition'],
    'genre' => 'mixte', 'joueurs_min' => 6, 'joueurs_max' => 18,
    'surface_type' => 'zone_libre', 'surface_largeur' => 15, 'surface_longueur' => 15,
    'duree_min' => 8, 'duree_max' => 14,
    'materiel' => [['type' => 'ballon', 'qte' => 12]],
    'description_deroulement' => "Chacun un ballon. Progression : lâcher-reprise pied fort, puis alterné, puis cuisse-pied, puis en marchant. Défis personnels.",
    'consignes_coach' => "Ballon frappé sous le centre, cheville verrouillée. On compte ses records, on ne compare pas.",
    'criteres_reussite' => "Chaque joueur bat son record de la semaine précédente.",
    'variante_facile' => "Lâcher-reprise après un rebond.", 'variante_difficile' => "Séquence imposée tête-cuisse-pied-pied.",
    'geometrie' => ['zone' => ['type' => 'zone_libre', 'longueur' => 15, 'largeur' => 15],
        'joueurs' => [
            ['x' => 4, 'y' => 4, 'equipe' => 'neutre'], ['x' => 11, 'y' => 4, 'equipe' => 'neutre'],
            ['x' => 4, 'y' => 11, 'equipe' => 'neutre'], ['x' => 11, 'y' => 11, 'equipe' => 'neutre'],
        ],
        'materiel' => [['type' => 'ballon', 'x' => 4, 'y' => 4], ['type' => 'ballon', 'x' => 11, 'y' => 4], ['type' => 'ballon', 'x' => 4, 'y' => 11], ['type' => 'ballon', 'x' => 11, 'y' => 11]]],
],
[
    'code' => 'ANA-PASSE-MUR', 'titre' => 'Une-deux avec un appui',
    'objectif_principal' => 'Jeu en remise, passe et va',
    'categorie_technique' => 'tactique', 'phase_easi' => 'analytique',
    'accents' => ['TA', 'TE'], 'tranches_age' => ['D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 6, 'joueurs_max' => 12,
    'surface_type' => 'quart', 'surface_largeur' => 18, 'surface_longueur' => 22,
    'duree_min' => 12, 'duree_max' => 18,
    'materiel' => [['type' => 'coupelle', 'qte' => 3], ['type' => 'ballon', 'qte' => 3]],
    'description_deroulement' => "Joueur A donne à l'appui B, part dans le dos du plot défenseur, reçoit la remise de B et conduit sur 5 m. Rotation A → B → colonne.",
    'consignes_coach' => "La passe appelle la course. Remise en une touche dans la course, jamais dans les pieds.",
    'criteres_reussite' => "Une-deux enchaînée sans contrôle sur la remise, 4 fois sur 5.",
    'variante_facile' => "Deux touches sur la remise.", 'variante_difficile' => "Ajouter un défenseur semi-actif sur l'appui.",
    'geometrie' => ['zone' => ['type' => 'quart', 'longueur' => 22, 'largeur' => 18],
        'joueurs' => [
            ['x' => 2, 'y' => 9, 'equipe' => 'A', 'label' => 'A'],
            ['x' => 11, 'y' => 4, 'equipe' => 'A', 'label' => 'B'],
        ],
        'materiel' => [['type' => 'coupelle', 'x' => 11, 'y' => 12]],
        'mouvements' => [
            ['from' => [2, 9], 'to' => [11, 4], 'type' => 'passe', 'ordre' => 1],
            ['from' => [2, 9], 'to' => [16, 9], 'type' => 'course', 'ordre' => 1, 'acteur' => 'A'],
            ['from' => [11, 4], 'to' => [16, 9], 'type' => 'passe', 'ordre' => 2],
        ]],
],

/* ================================================= SITUATIONNEL (7) */
[
    'code' => 'SIT-CONS4V2', 'titre' => 'Conservation 4 contre 2',
    'objectif_principal' => 'Garder le ballon sous pression, orientation du soutien',
    'categorie_technique' => 'tactique', 'phase_easi' => 'situatif',
    'accents' => ['TA', 'TE'], 'tranches_age' => ['E', 'D'], 'filieres' => ['loisir', 'competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 6, 'joueurs_max' => 14,
    'surface_type' => 'quart', 'surface_largeur' => 16, 'surface_longueur' => 16,
    'duree_min' => 12, 'duree_max' => 22,
    'materiel' => [['type' => 'coupelle', 'qte' => 4], ['type' => 'ballon', 'qte' => 2]],
    'description_deroulement' => "Carré, 4 conservent contre 2. À la récupération, les 2 défenseurs changent avec ceux qui ont provoqué la perte. Compter les passes.",
    'consignes_coach' => "Toujours deux solutions au porteur, une courte une longue. Bouger APRÈS la passe. Écarter le jeu quand on a le ballon.",
    'criteres_reussite' => "10 passes consécutives = 1 point pour les conservateurs.",
    'variante_facile' => "5 contre 2, deux touches.", 'variante_difficile' => "Une touche, ou terrain réduit à 12 m.",
    'geometrie' => ['zone' => ['type' => 'quart', 'longueur' => 16, 'largeur' => 16],
        'joueurs' => [
            ['x' => 2, 'y' => 2, 'equipe' => 'A', 'label' => '1'], ['x' => 14, 'y' => 2, 'equipe' => 'A', 'label' => '2'],
            ['x' => 14, 'y' => 14, 'equipe' => 'A', 'label' => '3'], ['x' => 2, 'y' => 14, 'equipe' => 'A', 'label' => '4'],
            ['x' => 7, 'y' => 7, 'equipe' => 'B', 'label' => '1'], ['x' => 9, 'y' => 10, 'equipe' => 'B', 'label' => '2'],
        ],
        'mouvements' => [
            ['from' => [2, 2], 'to' => [14, 2], 'type' => 'passe', 'ordre' => 1],
            ['from' => [14, 2], 'to' => [14, 14], 'type' => 'passe', 'ordre' => 2],
            ['from' => [14, 14], 'to' => [2, 14], 'type' => 'passe', 'ordre' => 3],
        ]],
],
[
    'code' => 'SIT-2V1', 'titre' => 'Supériorité 2 contre 1 vers un but',
    'objectif_principal' => 'Fixer et servir, prise de décision passe ou dribble',
    'categorie_technique' => 'tactique', 'phase_easi' => 'situatif',
    'accents' => ['TA'], 'tranches_age' => ['E', 'D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 6, 'joueurs_max' => 15,
    'surface_type' => 'demi', 'surface_largeur' => 25, 'surface_longueur' => 25,
    'duree_min' => 14, 'duree_max' => 22,
    'materiel' => [['type' => 'but', 'qte' => 1], ['type' => 'cone', 'qte' => 2], ['type' => 'ballon', 'qte' => 5]],
    'description_deroulement' => "Deux attaquants partent contre un défenseur, but sur grande cage avec gardien. Le défenseur démarre légèrement en retard. Rotation rapide.",
    'consignes_coach' => "Le porteur attaque le défenseur pour le fixer, puis sert au bon moment. Le non-porteur écarte et propose la profondeur.",
    'criteres_reussite' => "But marqué en moins de 8 secondes après le départ.",
    'variante_facile' => "Défenseur passif.", 'variante_difficile' => "Départ des deux joueurs à la même ligne que le défenseur.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 25, 'largeur' => 25],
        'joueurs' => [
            ['x' => 3, 'y' => 8, 'equipe' => 'A', 'label' => '1'], ['x' => 3, 'y' => 17, 'equipe' => 'A', 'label' => '2'],
            ['x' => 12, 'y' => 13, 'equipe' => 'B', 'label' => '1'],
            ['x' => 24, 'y' => 12, 'equipe' => 'gardien', 'label' => 'G'],
        ],
        'materiel' => [['type' => 'but', 'x' => 25, 'y' => 12]],
        'mouvements' => [
            ['from' => [3, 8], 'to' => [13, 10], 'type' => 'conduite', 'ordre' => 1, 'acteur' => '1'],
            ['from' => [13, 10], 'to' => [16, 17], 'type' => 'passe', 'ordre' => 2],
            ['from' => [16, 17], 'to' => [25, 12], 'type' => 'tir', 'ordre' => 3],
        ]],
],
[
    'code' => 'SIT-3V3-APPUIS', 'titre' => '3 contre 3 avec appuis extérieurs',
    'objectif_principal' => 'Utiliser les appuis, changer le point de jeu',
    'categorie_technique' => 'tactique', 'phase_easi' => 'situatif',
    'accents' => ['TA'], 'tranches_age' => ['D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 8, 'joueurs_max' => 14,
    'surface_type' => 'demi', 'surface_largeur' => 25, 'surface_longueur' => 30,
    'duree_min' => 14, 'duree_max' => 22,
    'materiel' => [['type' => 'coupelle', 'qte' => 6], ['type' => 'ballon', 'qte' => 3]],
    'description_deroulement' => "3 contre 3 au centre, un appui neutre sur chaque côté. Objectif : relier les deux appuis en 4 passes maxi sans perdre le ballon.",
    'consignes_coach' => "Chercher l'appui à l'opposé de la pression. Un joueur se propose toujours entre les lignes.",
    'criteres_reussite' => "Relier les deux appuis 3 fois dans la série.",
    'variante_facile' => "Appuis à deux touches, terrain plus large.", 'variante_difficile' => "Appuis à une touche, 3 passes maxi.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 30, 'largeur' => 25],
        'joueurs' => [
            ['x' => 10, 'y' => 8, 'equipe' => 'A', 'label' => '1'], ['x' => 15, 'y' => 13, 'equipe' => 'A', 'label' => '2'], ['x' => 10, 'y' => 18, 'equipe' => 'A', 'label' => '3'],
            ['x' => 18, 'y' => 9, 'equipe' => 'B', 'label' => '1'], ['x' => 20, 'y' => 16, 'equipe' => 'B', 'label' => '2'], ['x' => 14, 'y' => 20, 'equipe' => 'B', 'label' => '3'],
            ['x' => 2, 'y' => 13, 'equipe' => 'neutre', 'label' => 'A'], ['x' => 28, 'y' => 13, 'equipe' => 'neutre', 'label' => 'B'],
        ],
        'mouvements' => [
            ['from' => [10, 8], 'to' => [2, 13], 'type' => 'passe', 'ordre' => 1],
            ['from' => [2, 13], 'to' => [10, 18], 'type' => 'passe', 'ordre' => 2],
            ['from' => [10, 18], 'to' => [28, 13], 'type' => 'passe', 'ordre' => 3],
        ]],
],
[
    'code' => 'SIT-TRANSITION', 'titre' => 'Transition 3+1 contre 3',
    'objectif_principal' => 'Réaction immédiate à la perte et à la récupération',
    'categorie_technique' => 'tactique', 'phase_easi' => 'situatif',
    'accents' => ['TA', 'ME'], 'tranches_age' => ['D'], 'filieres' => ['elite', 'competition'],
    'genre' => 'mixte', 'joueurs_min' => 8, 'joueurs_max' => 14,
    'surface_type' => 'demi', 'surface_largeur' => 24, 'surface_longueur' => 28,
    'duree_min' => 14, 'duree_max' => 22,
    'materiel' => [['type' => 'mini_but', 'qte' => 2], ['type' => 'ballon', 'qte' => 4]],
    'description_deroulement' => "3 contre 3 + un joker qui joue toujours avec l'équipe en possession. Deux mini-buts par équipe. À la perte, réaction immédiate pendant 5 s.",
    'consignes_coach' => "À la récupération : première passe vers l'avant. À la perte : le plus proche presse, les autres cadenassent.",
    'criteres_reussite' => "Récupération dans les 5 secondes suivant une perte, 3 fois.",
    'variante_facile' => "Joker à deux touches.", 'variante_difficile' => "Pas de joker, 3 contre 3 strict.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 28, 'largeur' => 24],
        'joueurs' => [
            ['x' => 8, 'y' => 8, 'equipe' => 'A', 'label' => '1'], ['x' => 12, 'y' => 14, 'equipe' => 'A', 'label' => '2'], ['x' => 8, 'y' => 19, 'equipe' => 'A', 'label' => '3'],
            ['x' => 16, 'y' => 10, 'equipe' => 'B', 'label' => '1'], ['x' => 18, 'y' => 16, 'equipe' => 'B', 'label' => '2'], ['x' => 14, 'y' => 20, 'equipe' => 'B', 'label' => '3'],
            ['x' => 13, 'y' => 11, 'equipe' => 'neutre', 'label' => 'J'],
        ],
        'materiel' => [['type' => 'mini_but', 'x' => 0, 'y' => 8], ['type' => 'mini_but', 'x' => 0, 'y' => 16], ['type' => 'mini_but', 'x' => 28, 'y' => 8], ['type' => 'mini_but', 'x' => 28, 'y' => 16]],
        'mouvements' => [
            ['from' => [8, 8], 'to' => [13, 11], 'type' => 'passe', 'ordre' => 1],
            ['from' => [13, 11], 'to' => [8, 19], 'type' => 'passe', 'ordre' => 2],
        ]],
],
[
    'code' => 'SIT-VAGUES', 'titre' => 'Attaque-défense par vagues 3 contre 2',
    'objectif_principal' => 'Finir vite l\'attaque, défendre en infériorité',
    'categorie_technique' => 'jeu', 'phase_easi' => 'situatif',
    'accents' => ['TA'], 'tranches_age' => ['E', 'D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 8, 'joueurs_max' => 16,
    'surface_type' => 'demi', 'surface_largeur' => 30, 'surface_longueur' => 32,
    'duree_min' => 14, 'duree_max' => 24,
    'materiel' => [['type' => 'but', 'qte' => 1], ['type' => 'ballon', 'qte' => 6]],
    'description_deroulement' => "Trois attaquants partent contre deux défenseurs vers un but gardé. Dès que l'action se termine, une nouvelle vague part de l'autre côté.",
    'consignes_coach' => "Attaquer dans les 6 secondes. Largeur maximale pour étirer les deux défenseurs. Défenseurs : temporiser et fermer l'axe.",
    'criteres_reussite' => "Au moins 1 tir cadré par attaque.",
    'variante_facile' => "3 contre 1.", 'variante_difficile' => "3 contre 3, un défenseur qui rentre en retard.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 32, 'largeur' => 30],
        'joueurs' => [
            ['x' => 4, 'y' => 6, 'equipe' => 'A', 'label' => '1'], ['x' => 4, 'y' => 15, 'equipe' => 'A', 'label' => '2'], ['x' => 4, 'y' => 24, 'equipe' => 'A', 'label' => '3'],
            ['x' => 16, 'y' => 11, 'equipe' => 'B', 'label' => '1'], ['x' => 16, 'y' => 19, 'equipe' => 'B', 'label' => '2'],
            ['x' => 30, 'y' => 15, 'equipe' => 'gardien', 'label' => 'G'],
        ],
        'materiel' => [['type' => 'but', 'x' => 32, 'y' => 15]],
        'mouvements' => [
            ['from' => [4, 15], 'to' => [14, 8], 'type' => 'passe', 'ordre' => 1],
            ['from' => [14, 8], 'to' => [22, 20], 'type' => 'passe', 'ordre' => 2],
            ['from' => [22, 20], 'to' => [32, 15], 'type' => 'tir', 'ordre' => 3],
        ]],
],
[
    'code' => 'SIT-ZONE', 'titre' => 'Jeu de position 4 contre 4 + 3',
    'objectif_principal' => 'Occuper l\'espace, jouer entre les lignes',
    'categorie_technique' => 'tactique', 'phase_easi' => 'situatif',
    'accents' => ['TA'], 'tranches_age' => ['D'], 'filieres' => ['elite'],
    'genre' => 'mixte', 'joueurs_min' => 10, 'joueurs_max' => 16,
    'surface_type' => 'demi', 'surface_largeur' => 28, 'surface_longueur' => 26,
    'duree_min' => 16, 'duree_max' => 24,
    'materiel' => [['type' => 'coupelle', 'qte' => 8], ['type' => 'ballon', 'qte' => 3]],
    'description_deroulement' => "Rectangle divisé en 3 zones. 4 contre 4 dans la zone centrale + 3 relayeurs sur les côtés. L'équipe en possession cherche à faire circuler d'une zone à l'autre.",
    'consignes_coach' => "Un joueur minimum par zone en possession. Chercher le joueur libre à l'opposé. On joue vite quand la ligne est cassée.",
    'criteres_reussite' => "Traverser les 3 zones en conservation 3 fois.",
    'variante_facile' => "Relayeurs à deux touches.", 'variante_difficile' => "Interdiction de rejouer dans la zone d'où vient le ballon.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 26, 'largeur' => 28],
        'joueurs' => [
            ['x' => 9, 'y' => 8, 'equipe' => 'A', 'label' => '1'], ['x' => 13, 'y' => 13, 'equipe' => 'A', 'label' => '2'], ['x' => 9, 'y' => 18, 'equipe' => 'A', 'label' => '3'], ['x' => 5, 'y' => 13, 'equipe' => 'A', 'label' => '4'],
            ['x' => 15, 'y' => 9, 'equipe' => 'B', 'label' => '1'], ['x' => 17, 'y' => 15, 'equipe' => 'B', 'label' => '2'], ['x' => 13, 'y' => 20, 'equipe' => 'B', 'label' => '3'], ['x' => 11, 'y' => 6, 'equipe' => 'B', 'label' => '4'],
            ['x' => 2, 'y' => 8, 'equipe' => 'neutre'], ['x' => 24, 'y' => 14, 'equipe' => 'neutre'], ['x' => 13, 'y' => 26, 'equipe' => 'neutre'],
        ],
        'mouvements' => [
            ['from' => [9, 8], 'to' => [5, 13], 'type' => 'passe', 'ordre' => 1],
            ['from' => [5, 13], 'to' => [24, 14], 'type' => 'passe', 'ordre' => 2],
        ]],
],
[
    'code' => 'SIT-COULOIRS', 'titre' => 'Attaque des couloirs et centres',
    'objectif_principal' => 'Débordement et coordination avec le centre',
    'categorie_technique' => 'tactique', 'phase_easi' => 'situatif',
    'accents' => ['TA', 'TE'], 'tranches_age' => ['D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 8, 'joueurs_max' => 16,
    'surface_type' => 'demi', 'surface_largeur' => 34, 'surface_longueur' => 26,
    'duree_min' => 14, 'duree_max' => 22,
    'materiel' => [['type' => 'but', 'qte' => 1], ['type' => 'coupelle', 'qte' => 4], ['type' => 'ballon', 'qte' => 5]],
    'description_deroulement' => "Milieu lance le côté, l'ailier déborde et centre, deux attaquants viennent conclure aux premier et second poteau. Défenseurs en retard.",
    'consignes_coach' => "Centre devant le but, jamais derrière. Un attaquant premier poteau, un deuxième poteau, un en retrait.",
    'criteres_reussite' => "3 centres exploitables sur 5, au moins 1 but.",
    'variante_facile' => "Sans défenseurs.", 'variante_difficile' => "Deux défenseurs actifs dans la surface.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 26, 'largeur' => 34],
        'joueurs' => [
            ['x' => 6, 'y' => 17, 'equipe' => 'A', 'label' => '1'],
            ['x' => 12, 'y' => 3, 'equipe' => 'A', 'label' => '2'],
            ['x' => 20, 'y' => 14, 'equipe' => 'A', 'label' => '3'], ['x' => 20, 'y' => 22, 'equipe' => 'A', 'label' => '4'],
            ['x' => 25, 'y' => 17, 'equipe' => 'gardien', 'label' => 'G'],
        ],
        'materiel' => [['type' => 'but', 'x' => 26, 'y' => 17]],
        'mouvements' => [
            ['from' => [6, 17], 'to' => [12, 3], 'type' => 'passe', 'ordre' => 1],
            ['from' => [12, 3], 'to' => [22, 6], 'type' => 'conduite', 'ordre' => 2, 'acteur' => '2'],
            ['from' => [22, 6], 'to' => [21, 16], 'type' => 'passe', 'ordre' => 3],
            ['from' => [21, 16], 'to' => [26, 17], 'type' => 'tir', 'ordre' => 4],
        ]],
],

/* ================================================= JEU / INTÉGRÉ (7) */
[
    'code' => 'JEU-4V4-4BUTS', 'titre' => 'Jeu 4 contre 4 à quatre buts',
    'objectif_principal' => 'Changer d\'axe d\'attaque, lever la tête',
    'categorie_technique' => 'jeu', 'phase_easi' => 'integre',
    'accents' => ['TA'], 'tranches_age' => ['E', 'D'], 'filieres' => ['loisir', 'competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 8, 'joueurs_max' => 16,
    'surface_type' => 'demi', 'surface_largeur' => 30, 'surface_longueur' => 25,
    'duree_min' => 14, 'duree_max' => 24,
    'materiel' => [['type' => 'mini_but', 'qte' => 4], ['type' => 'ballon', 'qte' => 4]],
    'description_deroulement' => "Chaque équipe défend deux buts et en attaque deux (un dans chaque coin opposé). But en conduite dans la cage ou passe reçue derrière.",
    'consignes_coach' => "Quand un but est verrouillé, on bascule vers l'autre. Écarter le jeu, un joueur toujours à l'opposé.",
    'criteres_reussite' => "Marquer dans les deux buts adverses sur une même possession de série.",
    'variante_facile' => "Buts plus larges, deux touches.", 'variante_difficile' => "But validé seulement après passe dans la course.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 25, 'largeur' => 30],
        'joueurs' => [
            ['x' => 8, 'y' => 8, 'equipe' => 'A', 'label' => '1'], ['x' => 8, 'y' => 22, 'equipe' => 'A', 'label' => '2'], ['x' => 4, 'y' => 15, 'equipe' => 'A', 'label' => '3'], ['x' => 12, 'y' => 15, 'equipe' => 'A', 'label' => '4'],
            ['x' => 17, 'y' => 8, 'equipe' => 'B', 'label' => '1'], ['x' => 17, 'y' => 22, 'equipe' => 'B', 'label' => '2'], ['x' => 21, 'y' => 15, 'equipe' => 'B', 'label' => '3'], ['x' => 13, 'y' => 15, 'equipe' => 'B', 'label' => '4'],
        ],
        'materiel' => [['type' => 'mini_but', 'x' => 0, 'y' => 6], ['type' => 'mini_but', 'x' => 0, 'y' => 24], ['type' => 'mini_but', 'x' => 25, 'y' => 6], ['type' => 'mini_but', 'x' => 25, 'y' => 24]],
        'mouvements' => [
            ['from' => [8, 8], 'to' => [12, 15], 'type' => 'passe', 'ordre' => 1],
            ['from' => [12, 15], 'to' => [8, 22], 'type' => 'passe', 'ordre' => 2],
        ]],
],
[
    'code' => 'JEU-5V5-GB', 'titre' => 'Match 5 contre 5 avec gardiens',
    'objectif_principal' => 'Réinvestir la séance dans le jeu réel',
    'categorie_technique' => 'jeu', 'phase_easi' => 'integre',
    'accents' => ['TA', 'ME'], 'tranches_age' => ['E', 'D'], 'filieres' => ['loisir', 'competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 8, 'joueurs_max' => 14,
    'surface_type' => 'demi', 'surface_largeur' => 34, 'surface_longueur' => 45,
    'duree_min' => 15, 'duree_max' => 30,
    'materiel' => [['type' => 'but', 'qte' => 2], ['type' => 'ballon', 'qte' => 5]],
    'description_deroulement' => "Match libre 5 contre 5 sur demi-terrain, deux grandes cages, gardiens. Le coach relance vite, laisse jouer, intervient seulement sur le thème du jour.",
    'consignes_coach' => "Rappeler l'objectif de la séance en une phrase avant. Corriger sur image forte, pas en continu.",
    'criteres_reussite' => "Le thème travaillé apparaît spontanément 3 fois dans le jeu.",
    'variante_facile' => "Terrain plus court, hors-jeu supprimé.", 'variante_difficile' => "Deux touches maximum pour toute l'équipe.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 45, 'largeur' => 34],
        'joueurs' => [
            ['x' => 12, 'y' => 10, 'equipe' => 'A', 'label' => '1'], ['x' => 12, 'y' => 24, 'equipe' => 'A', 'label' => '2'], ['x' => 20, 'y' => 17, 'equipe' => 'A', 'label' => '3'], ['x' => 8, 'y' => 17, 'equipe' => 'A', 'label' => '4'],
            ['x' => 25, 'y' => 10, 'equipe' => 'B', 'label' => '1'], ['x' => 25, 'y' => 24, 'equipe' => 'B', 'label' => '2'], ['x' => 30, 'y' => 17, 'equipe' => 'B', 'label' => '3'], ['x' => 22, 'y' => 17, 'equipe' => 'B', 'label' => '4'],
            ['x' => 3, 'y' => 17, 'equipe' => 'gardien', 'label' => 'G'], ['x' => 42, 'y' => 17, 'equipe' => 'gardien', 'label' => 'G'],
        ],
        'materiel' => [['type' => 'but', 'x' => 0, 'y' => 17], ['type' => 'but', 'x' => 45, 'y' => 17]],
        'mouvements' => [
            ['from' => [12, 10], 'to' => [20, 17], 'type' => 'passe', 'ordre' => 1],
            ['from' => [20, 17], 'to' => [12, 24], 'type' => 'passe', 'ordre' => 2],
        ]],
],
[
    'code' => 'JEU-CONS-CIBLE', 'titre' => 'Conservation avec but sur passe dans la cible',
    'objectif_principal' => 'Conserver pour progresser, pas pour conserver',
    'categorie_technique' => 'jeu', 'phase_easi' => 'integre',
    'accents' => ['TA'], 'tranches_age' => ['D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 8, 'joueurs_max' => 14,
    'surface_type' => 'demi', 'surface_largeur' => 28, 'surface_longueur' => 30,
    'duree_min' => 14, 'duree_max' => 22,
    'materiel' => [['type' => 'coupelle', 'qte' => 8], ['type' => 'ballon', 'qte' => 3]],
    'description_deroulement' => "4 contre 4 (ou 5 contre 5). Point marqué en trouvant un partenaire dans une des deux zones-cibles adverses par une passe. Interdiction de rester dans la cible.",
    'consignes_coach' => "Attirer la pression d'un côté pour libérer l'autre. La passe dans la cible se prépare 2 passes avant.",
    'criteres_reussite' => "3 passes réussies dans une cible.",
    'variante_facile' => "Cibles plus grandes.", 'variante_difficile' => "Passe dans la cible seulement de volée ou après une-deux.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 30, 'largeur' => 28],
        'joueurs' => [
            ['x' => 10, 'y' => 9, 'equipe' => 'A', 'label' => '1'], ['x' => 14, 'y' => 15, 'equipe' => 'A', 'label' => '2'], ['x' => 10, 'y' => 21, 'equipe' => 'A', 'label' => '3'], ['x' => 6, 'y' => 15, 'equipe' => 'A', 'label' => '4'],
            ['x' => 18, 'y' => 10, 'equipe' => 'B', 'label' => '1'], ['x' => 20, 'y' => 17, 'equipe' => 'B', 'label' => '2'], ['x' => 15, 'y' => 22, 'equipe' => 'B', 'label' => '3'], ['x' => 13, 'y' => 7, 'equipe' => 'B', 'label' => '4'],
        ],
        'mouvements' => [
            ['from' => [10, 9], 'to' => [6, 15], 'type' => 'passe', 'ordre' => 1],
            ['from' => [6, 15], 'to' => [10, 21], 'type' => 'passe', 'ordre' => 2],
            ['from' => [10, 21], 'to' => [27, 21], 'type' => 'passe', 'ordre' => 3],
        ]],
],
[
    'code' => 'JEU-3ZONES', 'titre' => 'Jeu à thème : sortie de balle propre',
    'objectif_principal' => 'Ressortir le ballon proprement sous pression',
    'categorie_technique' => 'jeu', 'phase_easi' => 'integre',
    'accents' => ['TA'], 'tranches_age' => ['D'], 'filieres' => ['elite'],
    'genre' => 'mixte', 'joueurs_min' => 10, 'joueurs_max' => 16,
    'surface_type' => 'demi', 'surface_largeur' => 34, 'surface_longueur' => 40,
    'duree_min' => 16, 'duree_max' => 26,
    'materiel' => [['type' => 'but', 'qte' => 2], ['type' => 'ballon', 'qte' => 5]],
    'description_deroulement' => "Match 6 contre 6, gardiens. À chaque relance de gardien, l'équipe adverse presse. Point bonus si la balle est sortie de la première zone en jouant (pas en dégageant).",
    'consignes_coach' => "Le gardien joue court dès que possible. Les défenseurs s'écartent à la largeur de la surface. Un milieu vient recevoir dans l'axe.",
    'criteres_reussite' => "3 sorties de balle propres sous pression.",
    'variante_facile' => "Presseurs à distance de 3 m minimum.", 'variante_difficile' => "Dégagement long interdit, perte de balle = but encaissé.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 40, 'largeur' => 34],
        'joueurs' => [
            ['x' => 3, 'y' => 17, 'equipe' => 'gardien', 'label' => 'G'],
            ['x' => 8, 'y' => 8, 'equipe' => 'A', 'label' => '1'], ['x' => 8, 'y' => 26, 'equipe' => 'A', 'label' => '2'], ['x' => 14, 'y' => 17, 'equipe' => 'A', 'label' => '3'],
            ['x' => 12, 'y' => 12, 'equipe' => 'B', 'label' => '1'], ['x' => 12, 'y' => 22, 'equipe' => 'B', 'label' => '2'], ['x' => 18, 'y' => 17, 'equipe' => 'B', 'label' => '3'],
            ['x' => 37, 'y' => 17, 'equipe' => 'gardien', 'label' => 'G'],
        ],
        'materiel' => [['type' => 'but', 'x' => 0, 'y' => 17], ['type' => 'but', 'x' => 40, 'y' => 17]],
        'mouvements' => [
            ['from' => [3, 17], 'to' => [8, 8], 'type' => 'passe', 'ordre' => 1],
            ['from' => [8, 8], 'to' => [14, 17], 'type' => 'passe', 'ordre' => 2],
            ['from' => [14, 17], 'to' => [22, 17], 'type' => 'conduite', 'ordre' => 3, 'acteur' => '3'],
        ]],
],
[
    'code' => 'JEU-TOURNOI', 'titre' => 'Mini-tournoi 3 contre 3',
    'objectif_principal' => 'Engagement, plaisir, nombre de touches de balle',
    'categorie_technique' => 'jeu', 'phase_easi' => 'integre',
    'accents' => ['ME', 'TA'], 'tranches_age' => ['G', 'F', 'E'], 'filieres' => ['loisir', 'competition'],
    'genre' => 'mixte', 'joueurs_min' => 9, 'joueurs_max' => 18,
    'surface_type' => 'quart', 'surface_largeur' => 18, 'surface_longueur' => 24,
    'duree_min' => 15, 'duree_max' => 28,
    'materiel' => [['type' => 'mini_but', 'qte' => 4], ['type' => 'ballon', 'qte' => 4]],
    'description_deroulement' => "Trois équipes de 3. Deux jouent 2 minutes, la 3e attend. L'équipe qui encaisse sort, l'équipe qui attendait entre. Terrains courts, buts rapprochés.",
    'consignes_coach' => "Laisser jouer. Chaque enfant doit toucher beaucoup de ballons : petits effectifs, petits espaces.",
    'criteres_reussite' => "Tous les joueurs touchent le ballon au moins 10 fois par manche.",
    'variante_facile' => "Sans gardien, buts larges.", 'variante_difficile' => "But validé après 3 passes minimum.",
    'geometrie' => ['zone' => ['type' => 'quart', 'longueur' => 24, 'largeur' => 18],
        'joueurs' => [
            ['x' => 7, 'y' => 6, 'equipe' => 'A', 'label' => '1'], ['x' => 7, 'y' => 12, 'equipe' => 'A', 'label' => '2'], ['x' => 4, 'y' => 9, 'equipe' => 'A', 'label' => '3'],
            ['x' => 16, 'y' => 6, 'equipe' => 'B', 'label' => '1'], ['x' => 16, 'y' => 12, 'equipe' => 'B', 'label' => '2'], ['x' => 19, 'y' => 9, 'equipe' => 'B', 'label' => '3'],
        ],
        'groupes' => [['x' => 12, 'y' => 17, 'nombre' => 3]],
        'materiel' => [['type' => 'mini_but', 'x' => 0, 'y' => 9], ['type' => 'mini_but', 'x' => 24, 'y' => 9]],
        'mouvements' => [
            ['from' => [7, 6], 'to' => [4, 9], 'type' => 'passe', 'ordre' => 1],
            ['from' => [4, 9], 'to' => [7, 12], 'type' => 'passe', 'ordre' => 2],
        ]],
],
[
    'code' => 'JEU-SUPERIORITE', 'titre' => 'Jeu 5 contre 4 : exploiter le surnombre',
    'objectif_principal' => 'Trouver et utiliser le joueur libre',
    'categorie_technique' => 'jeu', 'phase_easi' => 'integre',
    'accents' => ['TA'], 'tranches_age' => ['D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 9, 'joueurs_max' => 16,
    'surface_type' => 'demi', 'surface_largeur' => 30, 'surface_longueur' => 30,
    'duree_min' => 14, 'duree_max' => 22,
    'materiel' => [['type' => 'but', 'qte' => 1], ['type' => 'mini_but', 'qte' => 2], ['type' => 'ballon', 'qte' => 4]],
    'description_deroulement' => "5 attaquants contre 4 défenseurs + gardien. Les attaquants marquent dans la grande cage, les défenseurs dans deux mini-buts en contre.",
    'consignes_coach' => "Le surnombre se joue par la largeur et la vitesse de circulation. Un joueur libre à chaque passe, il faut le voir avant de recevoir.",
    'criteres_reussite' => "But marqué après avoir utilisé au moins deux fois le joueur libre.",
    'variante_facile' => "6 contre 4.", 'variante_difficile' => "5 contre 5, un attaquant devient joker offensif.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 30, 'largeur' => 30],
        'joueurs' => [
            ['x' => 6, 'y' => 6, 'equipe' => 'A', 'label' => '1'], ['x' => 6, 'y' => 24, 'equipe' => 'A', 'label' => '2'], ['x' => 12, 'y' => 15, 'equipe' => 'A', 'label' => '3'], ['x' => 16, 'y' => 8, 'equipe' => 'A', 'label' => '4'], ['x' => 16, 'y' => 22, 'equipe' => 'A', 'label' => '5'],
            ['x' => 18, 'y' => 12, 'equipe' => 'B', 'label' => '1'], ['x' => 18, 'y' => 19, 'equipe' => 'B', 'label' => '2'], ['x' => 22, 'y' => 9, 'equipe' => 'B', 'label' => '3'], ['x' => 22, 'y' => 22, 'equipe' => 'B', 'label' => '4'],
            ['x' => 28, 'y' => 15, 'equipe' => 'gardien', 'label' => 'G'],
        ],
        'materiel' => [['type' => 'but', 'x' => 30, 'y' => 15], ['type' => 'mini_but', 'x' => 0, 'y' => 8], ['type' => 'mini_but', 'x' => 0, 'y' => 22]],
        'mouvements' => [
            ['from' => [6, 6], 'to' => [12, 15], 'type' => 'passe', 'ordre' => 1],
            ['from' => [12, 15], 'to' => [16, 22], 'type' => 'passe', 'ordre' => 2],
            ['from' => [16, 22], 'to' => [30, 15], 'type' => 'tir', 'ordre' => 3],
        ]],
],
[
    'code' => 'JEU-LIBRE-THEME', 'titre' => 'Jeu libre orienté finition',
    'objectif_principal' => 'Multiplier les situations de tir',
    'categorie_technique' => 'jeu', 'phase_easi' => 'integre',
    'accents' => ['TE', 'TA'], 'tranches_age' => ['E', 'D'], 'filieres' => ['loisir', 'competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 8, 'joueurs_max' => 14,
    'surface_type' => 'demi', 'surface_largeur' => 32, 'surface_longueur' => 36,
    'duree_min' => 15, 'duree_max' => 26,
    'materiel' => [['type' => 'but', 'qte' => 2], ['type' => 'ballon', 'qte' => 6]],
    'description_deroulement' => "Match 5 contre 5 + gardiens. Un but compte double s'il est marqué en une touche, ou après un centre. Relances rapides pour enchaîner les attaques.",
    'consignes_coach' => "On ose tirer. Un attaquant se démarque toujours dans la surface. Frappe cadrée avant frappe puissante.",
    'criteres_reussite' => "Au moins 8 frappes cadrées cumulées dans la série.",
    'variante_facile' => "Gardiens qui relancent à la main uniquement.", 'variante_difficile' => "Tir autorisé seulement à l'entrée de la surface.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 36, 'largeur' => 32],
        'joueurs' => [
            ['x' => 10, 'y' => 9, 'equipe' => 'A', 'label' => '1'], ['x' => 10, 'y' => 23, 'equipe' => 'A', 'label' => '2'], ['x' => 16, 'y' => 16, 'equipe' => 'A', 'label' => '3'], ['x' => 7, 'y' => 16, 'equipe' => 'A', 'label' => '4'],
            ['x' => 21, 'y' => 10, 'equipe' => 'B', 'label' => '1'], ['x' => 21, 'y' => 22, 'equipe' => 'B', 'label' => '2'], ['x' => 25, 'y' => 16, 'equipe' => 'B', 'label' => '3'], ['x' => 18, 'y' => 16, 'equipe' => 'B', 'label' => '4'],
            ['x' => 3, 'y' => 16, 'equipe' => 'gardien', 'label' => 'G'], ['x' => 33, 'y' => 16, 'equipe' => 'gardien', 'label' => 'G'],
        ],
        'materiel' => [['type' => 'but', 'x' => 0, 'y' => 16], ['type' => 'but', 'x' => 36, 'y' => 16]],
        'mouvements' => [
            ['from' => [10, 9], 'to' => [16, 16], 'type' => 'passe', 'ordre' => 1],
            ['from' => [16, 16], 'to' => [26, 12], 'type' => 'passe', 'ordre' => 2],
            ['from' => [26, 12], 'to' => [36, 16], 'type' => 'tir', 'ordre' => 3],
        ]],
],

/* ================================================= GARDIEN (2) */
[
    'code' => 'GB-PRISES', 'titre' => 'Prises de balle et déplacements',
    'objectif_principal' => 'Technique de prise, position de base',
    'categorie_technique' => 'gardien', 'phase_easi' => 'analytique',
    'accents' => ['TE', 'CO'], 'tranches_age' => ['E', 'D'], 'filieres' => ['competition', 'elite'],
    'genre' => 'mixte', 'joueurs_min' => 2, 'joueurs_max' => 6,
    'surface_type' => 'quart', 'surface_largeur' => 12, 'surface_longueur' => 10,
    'duree_min' => 10, 'duree_max' => 18,
    'materiel' => [['type' => 'but', 'qte' => 1], ['type' => 'cone', 'qte' => 4], ['type' => 'ballon', 'qte' => 6]],
    'description_deroulement' => "Le coach envoie des ballons à hauteurs variées (au sol, mi-hauteur, poitrine). Le gardien se replace entre chaque, mains en W pour les ballons hauts, corps derrière pour les ballons au sol.",
    'consignes_coach' => "Toujours le corps derrière le ballon. Après la prise, ballon serré contre la poitrine. Se replacer sur la pointe des pieds.",
    'criteres_reussite' => "8 prises propres sur 10, sans ballon relâché.",
    'variante_facile' => "Ballons annoncés à l'avance.", 'variante_difficile' => "Deux ballons alternés, rythme rapide.",
    'geometrie' => ['zone' => ['type' => 'quart', 'longueur' => 10, 'largeur' => 12],
        'joueurs' => [
            ['x' => 8, 'y' => 6, 'equipe' => 'gardien', 'label' => 'G'],
            ['x' => 2, 'y' => 6, 'equipe' => 'neutre', 'label' => 'C'],
        ],
        'materiel' => [['type' => 'but', 'x' => 10, 'y' => 6]],
        'mouvements' => [['from' => [2, 6], 'to' => [8, 6], 'type' => 'passe', 'ordre' => 1]]],
],
[
    'code' => 'GB-RELANCE', 'titre' => 'Relances courtes du gardien',
    'objectif_principal' => 'Qualité et choix de la relance au pied',
    'categorie_technique' => 'gardien', 'phase_easi' => 'situatif',
    'accents' => ['TE', 'TA'], 'tranches_age' => ['D'], 'filieres' => ['elite', 'competition'],
    'genre' => 'mixte', 'joueurs_min' => 4, 'joueurs_max' => 8,
    'surface_type' => 'demi', 'surface_largeur' => 24, 'surface_longueur' => 18,
    'duree_min' => 12, 'duree_max' => 18,
    'materiel' => [['type' => 'but', 'qte' => 1], ['type' => 'coupelle', 'qte' => 4], ['type' => 'ballon', 'qte' => 5]],
    'description_deroulement' => "Le gardien a le ballon, deux défenseurs se proposent à droite et à gauche, un presseur oriente. Le gardien choisit le côté libre et relance au sol, le défenseur ressort en conduite.",
    'consignes_coach' => "Regarder les deux appuis avant de jouer. Passe appuyée sur le pied éloigné du presseur. Ne jamais jouer dans l'axe si l'attaquant est proche.",
    'criteres_reussite' => "5 relances propres du bon côté sur 6.",
    'variante_facile' => "Presseur passif.", 'variante_difficile' => "Deux presseurs, ajout d'un troisième appui dans l'axe.",
    'geometrie' => ['zone' => ['type' => 'demi', 'longueur' => 18, 'largeur' => 24],
        'joueurs' => [
            ['x' => 2, 'y' => 12, 'equipe' => 'gardien', 'label' => 'G'],
            ['x' => 8, 'y' => 4, 'equipe' => 'A', 'label' => '1'], ['x' => 8, 'y' => 20, 'equipe' => 'A', 'label' => '2'],
            ['x' => 7, 'y' => 12, 'equipe' => 'B', 'label' => '1'],
        ],
        'materiel' => [['type' => 'but', 'x' => 0, 'y' => 12]],
        'mouvements' => [
            ['from' => [2, 12], 'to' => [8, 20], 'type' => 'passe', 'ordre' => 1],
            ['from' => [8, 20], 'to' => [16, 20], 'type' => 'conduite', 'ordre' => 2, 'acteur' => '2'],
        ]],
],

]];
